import axios from "axios";
import Head from "next/head";
import { GetServerSideProps } from "next/types";
import { ClearTinyLayout } from "../layouts/ClearTinyLayout";
import { IDBRouteDto } from "../types/dto";

interface Props {
  data: IDBRouteDto[];
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const getRoutes = await axios.get("http://localhost:3000/api/ping");
  const data = await getRoutes.data;
  return { props: { data } };
};

export default function Home({ data }: Props) {
  return (
    <div className="min-h-[100vh] ">
      <Head>
        <title>Vahui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClearTinyLayout links={[]}></ClearTinyLayout>
    </div>
  );
}
