import axios from "axios";
import Head from "next/head";
import { GetServerSideProps } from "next/types";
import { Loader } from "../components/Loader";
import { IDBRouteDto } from "../types/dto";
import { ClearTinyLayout } from "../layouts/ClearTinyLayout";
import { faker } from "@faker-js/faker";
import { useEffect } from "react";
import userpics from "../db/avatars.json";
import { randomFloatNumber } from "../helpers/randomNumber";

interface Props {
  data: IDBRouteDto[];
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const getRoutes = await axios.get("http://localhost:3000/api/ping");
  const data = await getRoutes.data;
  return { props: { data } };
};

export default function Home({ data }: Props) {
  return (
    <div className="min-h-[100vh] ">
      <Head>
        <title>Vahui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClearTinyLayout links={[]}>
        <div className="flex">
          <img src={userpics[randomFloatNumber(0, userpics.length)]} />
          <img src={userpics[randomFloatNumber(0, userpics.length)]} />
          <img src={userpics[randomFloatNumber(0, userpics.length)]} />
        </div>
        {!data && (
          <div>
            Routes <Loader />
          </div>
        )}
      </ClearTinyLayout>
    </div>
  );
}
